name: Build and Test

on:
  [push]
env:
  CARGO_TERM_COLOR: always
jobs:
  lib:
    name: Library
    defaults:
      run:
        working-directory: lib-contra
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  proc:
    name: Macros
    defaults:
      run:
        working-directory: proc-contra
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  contra:
    name: Crate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose